import os
import re
from datetime import datetime
from typing import List
from langchain_ollama import ChatOllama

from .models import Anomaly, Severity, AnomalyType
from .prompts import SYSTEM_PROMPT, SOP_PROMPT_TEMPLATE


SOP_TITLES = {
    AnomalyType.CRASH_LOOP_BACK_OFF: "Resolving CrashLoopBackOff in Kubernetes Pods",
    AnomalyType.OOM_KILLED: "Handling OOMKilled Out of Memory Pods",
    AnomalyType.IMAGE_PULL_BACK_OFF: "Fixing ImagePullBackOff Errors",
    AnomalyType.POD_PENDING: "Resolving Pending Pods in Kubernetes",
    AnomalyType.HIGH_RESTART_COUNT: "Managing High Pod Restart Counts",
    AnomalyType.DEPLOYMENT_DEGRADED: "Recovering Degraded Kubernetes Deployments",
    AnomalyType.NODE_NOT_READY: "Recovering Kubernetes Nodes in NotReady State",
    AnomalyType.CONTAINER_STUCK: "Resolving Containers Stuck in ContainerCreating State",
    AnomalyType.RESOURCE_PRESSURE: "Addressing Node Resource Pressure",
    AnomalyType.FAILED_SCHEDULING: "Fixing Failed Pod Scheduling",
    AnomalyType.EVICTED_POD: "Handling Evicted Pods",
    AnomalyType.UNKNOWN: "Kubernetes Unknown Pod Failure Investigation",
}


def _slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text.strip("-")


def generate_sop_content(anomaly: Anomaly, root_cause: str, solution: str) -> str:
    """Use Gemma 4 to generate SOP markdown content for an anomaly."""
    llm = ChatOllama(model="gemma4", temperature=0.2)

    title = SOP_TITLES.get(anomaly.type, f"Kubernetes {anomaly.type.value} Incident")

    prompt = SOP_PROMPT_TEMPLATE.format(
        anomaly_type=anomaly.type.value,
        severity=anomaly.severity.value,
        root_cause=(root_cause or "See analysis below")[:1000],
        solution=(solution or "See resolution steps below")[:1000],
        sop_title=title,
    )

    response = llm.invoke([
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ])
    return response.content


def save_sop(content: str, anomaly_type: AnomalyType, docs_dir: str = "docs") -> str:
    """Write SOP content to a markdown file and return its path."""
    os.makedirs(docs_dir, exist_ok=True)
    title = SOP_TITLES.get(anomaly_type, f"sop-{anomaly_type.value}")
    filename = f"SOP-{_slugify(title)}.md"
    filepath = os.path.join(docs_dir, filename)
    with open(filepath, "w") as f:
        f.write(content)
    return filepath


def generate_index_readme(sop_files: List[str], anomalies: List[Anomaly], docs_dir: str = "docs") -> str:
    """Generate docs/README.md as an index of all generated SOPs."""
    critical_count = sum(1 for a in anomalies if a.severity == Severity.CRITICAL)
    warning_count = sum(1 for a in anomalies if a.severity == Severity.WARNING)

    lines = [
        "# AIOps Incident SOPs",
        "",
        f"*Generated by AIOps CLI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Total Anomalies | {len(anomalies)} |",
        f"| Critical Issues | {critical_count} |",
        f"| Warnings | {warning_count} |",
        f"| SOPs Generated | {len(sop_files)} |",
        "",
        "## Generated SOPs",
        "",
    ]

    for filepath in sorted(sop_files):
        filename = os.path.basename(filepath)
        title = filename.replace("SOP-", "").replace(".md", "").replace("-", " ").title()
        lines.append(f"- [{title}]({filename})")

    lines += [
        "",
        "## Quick Reference: Anomaly Types",
        "",
        "| Anomaly | Severity | Typical Action |",
        "|---------|----------|----------------|",
        "| CrashLoopBackOff | CRITICAL | Check logs, fix app config or resource limits |",
        "| OOMKilled | CRITICAL | Increase memory limits in pod spec |",
        "| ImagePullBackOff | CRITICAL | Fix image name or registry credentials |",
        "| NodeNotReady | CRITICAL | Check node health, drain/cordon if needed |",
        "| DeploymentDegraded | WARNING | Check replica sets and pod events |",
        "| PodPending | WARNING | Check node resources, PVCs, and taints |",
        "| HighRestartCount | WARNING | Investigate liveness probe and app stability |",
        "| ResourcePressure | WARNING | Free up disk/memory or scale out nodes |",
        "",
        "## How to Use These SOPs",
        "",
        "1. Run `python main.py scan` to detect current anomalies.",
        "2. Find the matching SOP in this directory.",
        "3. Follow the step-by-step resolution process.",
        "4. Use `python main.py analyze` for deeper AI-driven investigation.",
        "5. Run `python main.py fix <pod> --namespace <ns>` for per-pod remediation.",
        "",
        "---",
        "*Auto-generated by [AIOps CLI](../README.md)*",
    ]

    filepath = os.path.join(docs_dir, "README.md")
    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    return filepath
